#ifndef QWEN_CORE_HF_CONFIG_H_
#define QWEN_CORE_HF_CONFIG_H_

#include <string>

#include "core/config.h"

namespace qwen {

// Reads and parses a Hugging Face config export (hf_config.json) generated by
// python_export/export_config.py.
//
// On success, returns true and writes the parsed ModelConfig to *out.
// On failure, returns false and writes a human-readable message to *err (if non-null).
bool try_load_hf_config_json(const std::string& path, ModelConfig* out, std::string* err);

// Convenience wrapper that throws std::runtime_error on failure.
ModelConfig load_hf_config_json(const std::string& path);

} // namespace qwen

#endif // QWEN_CORE_HF_CONFIG_H_
